name: Auto-update index.html

on:
  push:
    paths:
      - '*.strm'
      - 'update_index.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for pull --rebase

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run update_index.py
        run: python update_index.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes with rebase
        run: git pull origin main --rebase

      - name: Commit index.html if it changed
        run: |
          git add index.html
          git diff --cached --quiet || git commit -m "Auto-update index.html"

      - name: Push changes
        run: |
          git push origin main
