name: Auto-update index.html

on:
  push:
    paths:
      - '*.strm'
      - 'update_index.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for full git history and rebase

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Configure Git
        run: 
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes with rebase
        run: git pull origin main --rebase

      - name: Run update_index.py
        run: python update_index.py

      name: Auto Update index.html

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python (if needed)
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Run your script or update index.html
        run: |
          # Simulate a change to index.html (replace with your own logic)
          echo "<!-- Updated at $(date) -->" >> index.html

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git diff --cached --quiet || git commit -m "Auto-update index.html"

          # Pull the latest changes from origin/main with rebase to avoid conflicts
          git pull --rebase origin main

          # Push changes
          git push


