name: Auto-update index.html

on:
  push:
    paths:
      - '*.strm'
      - 'update_index.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update index.html
        run: python update_index.py

      - name: Commit and push index.html if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git diff --cached --quiet || git commit -m "Auto-update index.html"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/razzytest61/kodi-media-server.git HEAD:main
